### ISSUE TITLE
Lintly badge?

### ISSUE THREAD

**Issue by ivansabik** [grantmcconnaughey/Lintly#11]
Is there a way we can add lintly badge to our repos? Like this one:

![image](https://user-images.githubusercontent.com/815440/54154372-23adb000-4418-11e9-8080-9b8bd4c5b062.png)

Most like you just need to decide on one of these and add it to the README for instructions:
https://shields.io/

**Comment by grantmcconnaughey** [comment]
Hey Ivan. I'm pretty sure this feature would require a separate server to be running at all times, as well as a persisted backend to store results for each run.

The way CI services typically do this is by storing the results for each build against the `master` branch on the backend. Then that service has a URL, like `https://lintly.com/orgname/projectname/badge.jpg?branch=master`. When that URL is hit it looks up the current status (passing build, 70% test coverage, etc.) and redirects to the actual URL to render a badge from shields.io.

Since Lintly is just  CLI tool I'm not sure there would be a way for me to do this without standing up a web server and DB and storing all results there.

**Comment by ivansabik** [comment]
Ah got it makes sense, based on that it is not that easy as I thought :(
