### ISSUE TITLE
Post reviews as requests for changes

### ISSUE THREAD

**Issue by delissonjunio** [grantmcconnaughey/Lintly#17]
Right now Lintly posts issues in PRs as a plain review:

![Screen Shot 2020-01-19 at 01 31 07](https://user-images.githubusercontent.com/5759726/72674921-6c33f200-3a5b-11ea-96fb-60800d026a9f.png)

We'd rather have these be more authoritative and carry more weight. Even though the status report can block a PR, it makes even more sense that it's more than just a regular comment.

So I have a couple of questions:
1. As far as I can see, [this is the place](https://github.com/grantmcconnaughey/Lintly/blob/c5757ac42226d5c47db91f189d0f993b92e587dd/lintly/backends/github.py#L174) where the PR review is configured as a comment instead of a request for changes. According to [GitHub's documentation on the endpoint](https://developer.github.com/v3/pulls/reviews/#create-a-pull-request-review), a `REQUEST_CHANGES` value can be passed for `events`, configuring the review as such. Am I missing anything?
2. Do you see this as being something behind a flag on the cli?

I'm very interested in working on this (huuuge!) change 🙂

**Comment by grantmcconnaughey** [comment]
Hey @delissonjunio!

You're correct, the `create_pull_request_review` method will need to be updated to support this. One thing to keep in mind is that this method will need to request changes if there are violations and approve as soon as there are none.

In my opinion, reviews that approve/request changes should be the default behavior. Since Lintly is on a pre-1.x version (and assumed to be "beta") I think we're safe to make this the default behavior. I _do_ think we should introduce a flag like `--comment-only` to allow folks to revert to the previous behavior of only leaving comment reviews. [`cli.py` has some examples of how to do this](https://github.com/grantmcconnaughey/Lintly/blob/master/lintly/cli.py#L42) for leaving a commit status or not.

**Comment by delissonjunio** [comment]
:+1: I pushed up #18 implementing those changes and will close this issue now.
