### ISSUE TITLE
Integrate with GitHub checks

### ISSUE THREAD

**Issue by delissonjunio** [grantmcconnaughey/Lintly#19]
GitHub checks provides a built-in way to give details about problems line-by-line : https://developer.github.com/v3/checks/runs/

![checks-detailed](https://user-images.githubusercontent.com/5759726/72687548-8d3d2700-3add-11ea-82a9-eff2bc7a1b03.png)

Does it make sense to add support to this in Lintly? The limitation of always taking up linter output and directly and the lifetime of the tool might make this slightly difficult but it seems like an even more complete option instead of regular comments or PR reviews.

**Comment by grantmcconnaughey** [comment]
@delissonjunio I believe Checks must run from a GitHub App, not from OAuth tokens.

I talked about this with Kyle H, and luckily it does look like the token provided by GitHub Actions works for checks, since GitHub Actions is a GitHub App. So we'll want some way to only use the checks API if the user opts-into it, or perhaps if we detect that the user is calling Lintly from GitHub Actions.

**Comment by grantmcconnaughey** [comment]
Fixed in version 0.5.0
