### ISSUE TITLE
[Question] Suppress no violations message

### ISSUE THREAD

**Issue by yasir-din-cko** [grantmcconnaughey/Lintly#34]
Is it possible to suppress the following message coming from the tool:

![image](https://user-images.githubusercontent.com/52172948/91316819-3012fd80-e7b1-11ea-8d67-9dcf287a9709.png)

whilst allowing it to comment on issues if they exist?

**Comment by grantmcconnaughey** [comment]
@yasir-din-cko That would need to be a new configuration option, but I do think it's possible with GitHub's API.

Since you're using GitHub Actions another option is to use the `--use-checks` flag. That would use the Checks API instead. GitHub Actions will no longer review; instead it will only show violations under the Checks tab.

**Comment by grantmcconnaughey** [comment]
Just to confirm: a PR body is required by GitHub's pull request review API.

<img width="723" alt="Screen Shot 2020-10-17 at 1 56 07 PM" src="https://user-images.githubusercontent.com/4023140/96351386-8fd6a800-1080-11eb-93dd-98051fc99098.png">

For your use-case I'd look into using the `--use-checks` flag so that the Checks API is used instead. IMO it's a much nicer experience with Lintly.
